// Textos de los carruseles de VitalPet.
// *texto* = palabra destacada en gris (como en la web).
// Tipos de diapositiva: hook, text, big, steps, step, list, compare, specs, flow, diagram, photo, cta.

module.exports = [
  {
    id: '01-agua-de-ayer',
    titulo: 'Un filtro no convierte agua vieja en agua nueva',
    slides: [
      { t: 'hook', kicker: 'Lo que nadie te cuenta de las fuentes', h: 'Un filtro no convierte agua vieja en agua *nueva.*' },
      { t: 'flow', kicker: 'Fuente con filtro', h: 'Filtrar. Recircular. *Repetir.*',
        body: 'El agua pasa por el filtro y vuelve al mismo depósito. Una y otra vez, durante días.',
        items: [['drop', 'Agua'], ['filter', 'Filtro'], ['cycle', 'Mismo depósito'], ['paw', 'Tu gato bebe']] },
      { t: 'text', kicker: 'Cada vez que bebe', h: 'La saliva y los restos de comida vuelven *al depósito.*',
        body: 'El agua puede parecer limpia mientras la suciedad se acumula dentro.' },
      { t: 'text', kicker: 'El filtro', h: 'Reduce partículas. *No cambia el agua.*',
        body: 'Y encima hay que desmontar, lavar la bomba y cambiar el filtro. Si te saltas un paso, sigue girando la misma agua.' },
      { t: 'photo', dark: true, kicker: 'La solución VitalPet', h: 'Retira. Renueva. *Repite.*',
        body: 'Retira el agua usada a un depósito aparte y pone agua limpia en el cuenco.', img: 'producto.jpg' },
      { t: 'steps', dark: true, kicker: 'Así de simple', h: 'Agua nueva, *no reciclada.*',
        items: [['Retira', 'El agua usada pasa al depósito de agua sucia.'],
                ['Renueva', 'Cae agua limpia al cuenco de cerámica.'],
                ['Repite', 'Cada 6 h, o el intervalo que elijas en la pantalla.']] },
      { t: 'cta', h: 'Tu gato no tiene por qué beber *el agua de ayer.*', img: 'producto.jpg' },
    ],
  },
  {
    id: '02-cuanto-cuesta',
    titulo: '¿Cuánto te cuesta de verdad tu fuente?',
    slides: [
      { t: 'hook', kicker: 'Haz la cuenta', h: 'Tu fuente «barata» te sale *más cara* de lo que crees' },
      { t: 'big', kicker: 'Filtros de recambio', big: '50–70 €', h: 'al año',
        body: 'Según el modelo de fuente y cada cuánto cambies el filtro.' },
      { t: 'list', kicker: 'Y además', h: 'Tu tiempo *también cuenta.*', mark: 'x',
        items: ['Desmontar la fuente', 'Lavar el depósito y la bomba', 'Cambiar el filtro', 'Vaciar y rellenar', 'Montarla y comprobar que funciona'] },
      { t: 'big', dark: true, kicker: 'VitalPet', big: '0 €', h: 'en filtros',
        body: 'No lleva filtro. No hay recambios que comprar ni que recordar.' },
      { t: 'compare', kicker: 'Comparación', h: 'Fuente con filtro *vs VitalPet*',
        left: 'Con filtro', right: 'VitalPet',
        rows: [['Recircula la misma agua', 'Renueva el agua'],
               ['Filtros de recambio', 'Sin filtros'],
               ['Lavar la bomba a menudo', 'Programas y te olvidas'],
               ['Rellenar a mano a menudo', 'Depósito de 4,5 L*']],
        note: '*Hasta 1–2 semanas para un gato adulto o perro pequeño, según consumo.' },
      { t: 'cta', h: 'Deja de pagar filtros. *Renueva el agua.*', img: 'producto.jpg' },
    ],
  },
  {
    id: '03-como-funciona',
    titulo: 'Así funciona VitalPet',
    slides: [
      { t: 'photo', kicker: 'Te lo explico en 30 segundos', h: '¿Una fuente *sin filtro?*',
        body: 'Así funciona VitalPet. Desliza →', img: 'producto.jpg' },
      { t: 'diagram', kicker: 'Por dentro', h: 'Dos depósitos *separados.*',
        body: 'Uno para el agua limpia y otro para el agua usada.' },
      { t: 'step', n: '01', h: 'Retira', body: 'Pasado el tiempo que programes, el agua del cuenco se va al depósito de agua usada.' },
      { t: 'step', n: '02', h: 'Renueva', body: 'Cae agua limpia al cuenco de cerámica. La cantidad también la eliges tú.' },
      { t: 'step', n: '03', dark: true, h: 'Repite', body: 'Por ejemplo, cada 6 horas. Lo configuras una vez en la pantalla táctil y listo.' },
      { t: 'specs', kicker: 'En números', h: 'Hecha para *olvidarte.*',
        items: [['drop', '4,5 L', 'de capacidad'], ['calendar', '1–2 semanas', 'de agua*'],
                ['battery', '60 días', 'de batería**'], ['paw', '1–3', 'mascotas'],
                ['bowl', 'Cerámica', 'cuenco'], ['mute', 'Silenciosa', 'sin ruido molesto']],
        note: '*Gato adulto o perro pequeño, según consumo. **Según modelo y uso.' },
      { t: 'cta', h: 'Agua limpia. *Renovada sola.*', img: 'producto.jpg', sub: 'Disponible en Cream White y Gray White' },
    ],
  },
  {
    id: '04-pov-finde',
    titulo: 'POV: te vas el finde',
    slides: [
      { t: 'hook', kicker: 'POV', h: 'Te vas el finde y no tienes que pedirle a nadie que *le cambie el agua*' },
      { t: 'text', kicker: 'Antes', h: '«¿Te puedes pasar a cambiarle el agua?» *Otra vez.*' },
      { t: 'text', kicker: 'Antes', h: 'Y volver el domingo al cuenco *de anteayer.*' },
      { t: 'photo', dark: true, kicker: 'Ahora', h: 'Agua nueva *cada pocas horas.*',
        body: 'VitalPet retira el agua usada y la renueva sola, cuando tú lo programes.', img: 'producto.jpg' },
      { t: 'specs', kicker: 'Para que te vayas sin preocuparte', h: 'Autonomía *de verdad.*',
        items: [['drop', '4,5 L', 'de agua limpia'], ['calendar', '1–2 semanas', 'de autonomía*'],
                ['battery', 'Sin cables', 'hasta 60 días**'], ['cycle', 'Automática', 'tú eliges cada cuánto']],
        note: '*Gato adulto o perro pequeño, según consumo. **Según modelo y uso.' },
      { t: 'cta', h: 'Tú de viaje. *Él con agua fresca.*', img: 'producto.jpg' },
    ],
  },
  {
    id: '05-invierno-28',
    titulo: 'Agua templada en invierno',
    slides: [
      { t: 'hook', kicker: 'Llega el frío', h: '¿Tu gato bebe menos *en invierno?*' },
      { t: 'text', kicker: 'Es más común de lo que crees', h: 'A muchos no les gusta *el agua fría.*',
        body: 'Sobre todo a los gatos mayores o más sensibles.' },
      { t: 'big', dark: true, kicker: 'Modo calefacción', big: '28 °C', h: 'constantes',
        body: 'El modelo con calefacción mantiene el agua templada todo el día.' },
      { t: 'text', kicker: 'Lo mejor de los dos mundos', h: 'Templada *y renovada.*',
        body: 'Sigue funcionando igual: retira el agua usada y pone agua limpia en el cuenco.' },
      { t: 'list', kicker: 'Ideal para', h: '¿Es para *tu casa?*', mark: 'check',
        items: ['Casas frías en invierno', 'Terrazas y galerías', 'Gatos mayores', 'Mascotas que beben poco'] },
      { t: 'cta', h: 'Este invierno, *agua templada.*', img: 'producto.jpg', sub: 'Elige el modelo «Ceramic heating»' },
    ],
  },
];
